### PR TITLE
Apple intel integration

### PR DESCRIPTION
**Pull request by Schreezer**
## Summary
- Introduce the Apple Intelligence post-processing provider wired through a Swift FFI bridge so macOS + Apple Silicon users can clean transcripts fully on-device via FoundationModels.
- Extend Rust settings/actions plus React settings UI to detect Apple provider, auto-select prompts/models, and hide network-only controls while surfacing hardware requirements.

### CODE REVIEW

**Comment by Schreezer** [comment]
so i have been using this since the last commit, and its working well imo... surely adds latency since its apple's local model so atleast 3B but still better than loading a custom one since this will be loaded anyways if you have apple intelligence enabled

**Comment by cjpais** [comment]
I'm not able to get this to build on my Mac (Tahoe 26.1 (25B78))

```
error: failed to run custom build command for `handy v0.6.3 (/Users/cj/code/cjpais/Handy/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/cj/code/cjpais/Handy/src-tauri/target/debug/build/handy-fe8aeb4d6211958b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=apple_intelligence.swift
  cargo:rerun-if-changed=apple_intelligence_bridge.h

  --- stderr
  apple_intelligence.swift:7:16: error: external macro implementation type 'FoundationModelsMacros.GenerableMacro' could not be found for macro 'Generable(description:)'; plugin for module
 'FoundationModelsMacros' not found
    5 | @available(macOS 26.0, *)
    6 | @Generable
    7 | private struct CleanedTranscript: Sendable {
      |                `- error: external macro implementation type 'FoundationModelsMacros.GenerableMacro' could not be found for macro 'Generable(description:)'; plugin for module 'Found
ationModelsMacros' not found
    8 |     let cleanedText: String
    9 | }

  FoundationModels.Generable:4:145: note: 'Generable(description:)' declared here
  2 | @available(tvOS, unavailable)
  3 | @available(watchOS, unavailable)
  4 | @attached(extension, conformances: Generable, names: named(init(_:)), named(generatedContent)) @attached(member, names: arbitrary) public macro Generable(description: String? = nil)
= #externalMacro(module: "FoundationModelsMacros", type: "GenerableMacro")
    |                                                                                                                                                 `- note: 'Generable(description:)' dec
lared here

  apple_intelligence.swift:7:16: error: external macro implementation type 'FoundationModelsMacros.GenerableMacro' could not be found for macro 'Generable(description:)'; plugin for module
 'FoundationModelsMacros' not found
    5 | @available(macOS 26.0, *)
```

**Comment by Schreezer** [comment]
Could you please confirm the version of Xcode  you have? 
Command: xcode-select --version
xcode-select version 2412.
Command: xcodebuild -version
Xcode 26.1.1
Build version 17B100

Also working on a patch to allow the ones without the latest version to be able to build, my bad...

**Comment by cjpais** [comment]
Thanks for the callout something in my env with Xcode with messed up

**Comment by Schreezer** [comment]
I have also made changes to make sure it compiles for lower versions.

**Comment by cjpais** [comment]
I'm quite impressed by this set of changes. I haven't had to review it entirely, but I did test it on my Mac and it works pretty well out of the box for me. Give me some time to review, as well as make sure that CI still works with this. 

I think this is a great default option for MacOS, and might bring post-processing a little closer to prime-time for everyone

**Comment by dannysmith** [comment]
> I think this is a great default option for MacOS, and might bring post-processing a little closer to prime-time for everyone

I 💯 agree with this - as @Schreezer  says: it adds a bit of latency, but compared to other local models (which I don't want loaded all the time) it's much better. Works great for me (M2, macOS 26.0.1) and built with no issues.

**Comment by cjpais** [comment]
I just want to say a huge thanks for this @Schreezer, it's genuinely amazing

**Comment by AlexanderYastrebov** [comment]
I tried to follow [BUILD.md](https://github.com/cjpais/Handy/blob/1d4d6820f6139d1cba0eba3ad5ae830b6c5ebfc6/BUILD.md) instructions and got the same error as in https://github.com/cjpais/Handy/pull/391#issuecomment-3591494131

```
warning: handy@0.7.8: Building with Apple Intelligence support.
error: failed to run custom build command for `handy v0.7.8 (/Users/alexander/src/github.com/cjpais/Handy/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/alexander/src/github.com/cjpais/Handy/src-tauri/target/debug/build/handy-07df608c667ca410/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=swift/apple_intelligence.swift
  cargo:rerun-if-changed=swift/apple_intelligence_stub.swift
  cargo:rerun-if-changed=swift/apple_intelligence_bridge.h
  cargo:warning=Building with Apple Intelligence support.

  --- stderr
  swift/apple_intelligence.swift:7:16: error: external macro implementation type 'FoundationModelsMacros.GenerableMacro' could not be found for macro 'Generable(description:)'; plugin for module 'FoundationModelsMacros' not found
    5 | @available(macOS 26.0, *)
    6 | @Generable
    7 | private struct CleanedTranscript: Sendable {
      |                `- error: external macro implementation type 'FoundationModelsMacros.GenerableMacro' could not be found for macro 'Generable(description:)'; plugin for module 'FoundationModelsMacros' not found
    8 |     let cleanedText: String
    9 | }

  FoundationModels.Generable:4:145: note: 'Generable(description:)' declared here
  2 | @available(tvOS, unavailable)
  3 | @available(watchOS, unavailable)
  4 | @attached(extension, conformances: Generable, names: named(init(_:)), named(generatedContent)) @attached(member, names: arbitrary) public macro Generable(description: String? = nil) = #externalMacro(module: "FoundationModelsMacros", type: "GenerableMacro")
    |                                                                                                                                                 `- note: 'Generable(description:)' declared here

  swift/apple_intelligence.swift:7:16: error: external macro implementation type 'FoundationModelsMacros.GenerableMacro' could not be found for macro 'Generable(description:)'; plugin for module 'FoundationModelsMacros' not found
    5 | @available(macOS 26.0, *)
    6 | @Generable
    7 | private struct CleanedTranscript: Sendable {
      |                `- error: external macro implementation type 'FoundationModelsMacros.GenerableMacro' could not be found for macro 'Generable(description:)'; plugin for module 'FoundationModelsMacros' not found
    8 |     let cleanedText: String
    9 | }

  FoundationModels.Generable:4:145: note: 'Generable(description:)' declared here
  2 | @available(tvOS, unavailable)
  3 | @available(watchOS, unavailable)
  4 | @attached(extension, conformances: Generable, names: named(init(_:)), named(generatedContent)) @attached(member, names: arbitrary) public macro Generable(description: String? = nil) = #externalMacro(module: "FoundationModelsMacros", type: "GenerableMacro")
    |                                                                                                                                                 `- note: 'Generable(description:)' declared here

  swift/apple_intelligence.swift:99:52: error: instance method 'respond(to:generating:includeSchemaInPrompt:options:)' requires that 'CleanedTranscript' conform to 'Generable'
   97 | 
   98 |             do {
   99 |                 let structured = try await session.respond(
      |                                                    `- error: instance method 'respond(to:generating:includeSchemaInPrompt:options:)' requires that 'CleanedTranscript' conform to 'Generable'
  100 |                     to: swiftUserContent,
  101 |                     generating: CleanedTranscript.self

  FoundationModels.LanguageModelSession.respond:3:45: note: where 'Content' = 'CleanedTranscript'
  1 | class LanguageModelSession {
  2 | @discardableResult
  3 |   nonisolated(nonsending) final public func respond<Content>(to prompt: String, generating type: Content.Type = Content.self, includeSchemaInPrompt: Bool = true, options: GenerationOptions = GenerationOptions()) async throws -> LanguageModelSession.Response<Content> where Content : Generable}
    |                                             `- note: where 'Content' = 'CleanedTranscript'
  4 | 

  thread 'main' (44574234) panicked at build.rs:202:9:
  swiftc failed to compile swift/apple_intelligence.swift
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: script "tauri" exited with code 101
```
```
% xcode-select --version
xcode-select version 2410.
% xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
