### PR TITLE
fix: add required defaults option to plugin-store configuration

### PR DESCRIPTION
**Pull request by zenyr**
## Summary
Fixes a TypeScript compilation error introduced when updating @tauri-apps/plugin-store to v2.4.1.

The store plugin now requires the `defaults` property in StoreOptions, but the refreshSettings method was only passing `autoSave: false`. This caused a build failure.

## Changes
- Added `defaults: DEFAULT_SETTINGS` to the load() call in settingsStore.ts
- Ensures the store has proper default values when initialized

## Related
- Triggered by recent dependency updates (commit: dd40d8e)
- @tauri-apps/plugin-store v2.4.1 now requires `defaults` in StoreOptions

## Testing
✓ Build succeeds (vite build + tsc validation)

### CODE REVIEW

**Comment by cjpais** [comment]
Thank you, I appreciate you fixing this!
